In [2]:
import numpy as np
mydata = np.arange(0,20)
print(mydata)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [3]:
np.reshape(mydata,(5,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [4]:
MATR1 = np.reshape(mydata,(5,4),order='C')
MATR1  

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [8]:
#To get to number 10
MATR1[2,2]

10

In [9]:
MATR2 = np.reshape(mydata,(5,4),order='C')
MATR2  

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [10]:
#To get to number 10
MATR1[2,2]

10

In [11]:
 #OOP Concept
mydata.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [16]:
r1 = ["I","am","happy"]
r2 = ["What","a","day"]
r3 = [1,2,3]

In [17]:
a= [r1,r2,r3]

In [19]:
print(np.array(a))

[['I' 'am' 'happy']
 ['What' 'a' 'day']
 ['1' '2' '3']]
